# Generated by Django 4.2.4 on 2023-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_languageskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageskill',
            options={'ordering': ['-proficiency_level', 'language']},
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='proficiency_level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2'), ('native', 'Native')], max_length=20),
        ),
    ]
