# Generated by Django 4.2.4 on 2023-09-02 01:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_section_cta_text',
            field=models.CharField(blank=True, help_text='Text for the Call to Action button', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_section_heading',
            field=models.CharField(blank=True, help_text='First Section Heading', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_section_image',
            field=models.ForeignKey(blank=True, help_text='First Section Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_section_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='First Section Text'),
        ),
    ]
