# Generated by Django 4.2.4 on 2023-09-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_genericsettings_homepage_first_section_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_section_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action in the first section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
