# Generated by Django 4.2.4 on 2023-09-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0004_homepage_first_section_cta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_section_cta_link_2',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action in the first section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_section_cta_text_2',
            field=models.CharField(blank=True, help_text='Text for the Call to Action button', max_length=255),
        ),
    ]
