# Generated by Django 4.2.5 on 2023-12-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EntryPage',
        ),
        migrations.DeleteModel(
            name='PortfolioIndexPage',
        ),
    ]
